# Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    instance_group: 'server'

scrape_configs:
  - job_name: 'server_traefik'
    static_configs:
      - targets: ['traefik:8082']
        labels:
          service_name: 'traefik'
