services:
  ollama:
    image: docker.io/ollama/ollama:0.17.7
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama_private_net
      - ollama_public_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:

networks:
  ollama_private_net:
    internal: false
  ollama_public_net:
    internal: true
