services:
  ollama:
    image: ollama/ollama:${OLLAMA_VERSION}
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ollama_ingress
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data:

networks:
  ollama_ingress:
    name: ollama_ingress
