name: homelab_gateway

services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:2.11.1
    restart: unless-stopped
    environment:
      - CLOUDFLARE_API_TOKEN=${CF_DNS_API_TOKEN}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 2019:2019/tcp # for caddy metrics
    networks:
      - headscale_net

  headscale:
    image: docker.io/headscale/headscale:0.28.0
    restart: unless-stopped
    command: serve
    read_only: true
    tmpfs:
      - /var/run/headscale
    volumes:
      - ./headscale/config.yaml:/etc/headscale/config.yaml:ro
      - headscale_data:/var/lib/headscale
    ports:
      - 3478:3478/udp # for STUN
      - 9090:9090/tcp # for metrics
    networks:
      - headscale_net

  headplane:
    image: ghcr.io/tale/headplane:0.6.2
    restart: unless-stopped
    depends_on:
      - headscale
    volumes:
      - ./headplane/config.yaml:/etc/headplane/config.yaml:ro
      - ./headscale/config.yaml:/etc/headscale/config.yaml:ro
      - headplane_data:/var/lib/headplane
    networks:
      - headscale_net

  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:v1.7.6
    restart: unless-stopped
    environment:
      - COLLECTIONS=crowdsecurity/linux crowdsecurity/sshd crowdsecurity/caddy crowdsecurity/base-http-scenarios crowdsecurity/http-cve crowdsecurity/http-dos
    volumes:
      - crowdsec_config:/etc/crowdsec
      - ./crowdsec/acquis.d:/etc/crowdsec/acquis.d:ro
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - crowdsec_db:/var/lib/crowdsec/data
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog:ro
      - caddy_logs:/var/log/caddy:ro
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - crowdsec_net

networks:
  headscale_net:
  crowdsec_net:

volumes:
  caddy_data:
  caddy_config:
  caddy_logs:
  headscale_data:
  headplane_data:
  crowdsec_config:
  crowdsec_db:
