services:
  code_runner:
    image: docker.io/huakesh/code-runner:0.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "${PUID}:${PGID}"
    environment:
      API_TOKEN: ${CODERUNNER_API_TOKEN}
    networks:
      - code_runner_public_net
      - traefik_public_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.code_runner.entrypoints=websecure
      - traefik.http.routers.code_runner.rule=Host(`code-runner.server.${DOMAIN}`)
      - traefik.http.services.code_runner.loadbalancer.server.port=8080
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  code_runner_public_net:
    internal: true
