services:
  code_runner:
    image: docker.io/huakesh/code-runner:0.1
    restart: unless-stopped
    environment:
      API_TOKEN: ${CODERUNNER_API_TOKEN}
    networks:
      - code_runner_net
      - code_runner_ingress
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.code_runner.entrypoints=websecure
      - traefik.http.routers.code_runner.rule=Host(`code-runner.${DOMAIN}`)
      - traefik.http.services.code_runner.loadbalancer.server.port=8080

networks:
  code_runner_net:
    internal: true
  code_runner_ingress:
    internal: true
