services:
  code_runner:
    image: huakesh/code-runner:${CODERUNNER_VERSION}
    restart: unless-stopped
    environment:
      API_TOKEN: ${CODERUNNER_API_TOKEN}
    networks:
      - code_runner_ingress
    labels:
      - traefik.enable=true
      - traefik.http.routers.code_runner.rule=Host(`code-runner.${DOMAIN}`)
      - traefik.http.routers.code_runner.entrypoints=websecure
      - traefik.http.routers.code_runner.tls.certresolver=${TRAEFIK_CERT_RESOLVER}
      - traefik.http.routers.code_runner.tls.domains[0].main=code-runner.${DOMAIN}
      - traefik.http.services.code_runner.loadbalancer.server.port=8080
      - traefik.docker.network=code_runner_ingress

networks:
  code_runner_ingress:
    name: code_runner_ingress
