http:
  middlewares:
    private_only:
      ipWhiteList:
        sourceRange:
          - "100.64.0.0/10" # Headscale CGNAT range
    crowdsec:
      plugin:
        crowdsec_bouncer_traefik_plugin:
          enabled: true
          crowdsecMode: live
          crowdsecAppsecEnabled: true
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          crowdsecLapiScheme: http
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiKey: {{ env "CROWDSEC_LAPI_KEY" }}
