services:
  headscale:
    image: docker.io/headscale/headscale:0.28.0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "${PUID}:${PGID}"
    command: serve
    read_only: true
    tmpfs:
      - /var/run/headscale
    volumes:
      - ./headscale/config.yaml:/etc/headscale/config.yaml:ro
      - ./headscale/acls.hujson:/etc/headscale/acls.hujson:ro
      - headscale_data:/var/lib/headscale
    ports:
      - 3478:3478/udp # for STUN
    networks:
      - headscale_private_net
      - headscale_public_net
      - traefik_public_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.headscale.entrypoints=websecure
      - traefik.http.routers.headscale.rule=Host(`headscale.vpn.${DOMAIN}`)
      - traefik.http.services.headscale.loadbalancer.server.port=8080

  headplane:
    image: ghcr.io/tale/headplane:0.6.2
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "${PUID}:${PGID}"
    read_only: true
    depends_on:
      - headscale
    volumes:
      - ./headplane/config.yaml:/etc/headplane/config.yaml:ro
      - ./headscale/config.yaml:/etc/headscale/config.yaml:ro
      - ./headscale/acls.hujson:/etc/headscale/acls.hujson:ro
      - headplane_data:/var/lib/headplane
    networks:
      - headscale_private_net
      - traefik_public_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.headplane.entrypoints=websecure
      - traefik.http.routers.headplane.middlewares=private_only@file
      - traefik.http.routers.headplane.rule=Host(`headplane.vpn.${DOMAIN}`)
      - traefik.http.services.headplane.loadbalancer.server.port=3000

volumes:
  headscale_data:
  headplane_data:

networks:
  headscale_private_net:
    internal: false
  headscale_public_net:
    internal: true
