services:
  headscale:
    image: docker.io/headscale/headscale:0.28.0
    restart: unless-stopped
    command: serve
    read_only: true
    tmpfs:
      - /var/run/headscale
    volumes:
      - ./headscale/config.yaml:/etc/headscale/config.yaml:ro
      - ./headscale/acls.hujson:/etc/headscale/acls.hujson:ro
      - headscale_data:/var/lib/headscale
    ports:
      - 3478:3478/udp # for STUN
    networks:
      - headscale_private_net
      - traefik_public_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.headscale.entrypoints=websecure_private,websecure_public
      - traefik.http.routers.headscale.rule=Host(`vpn.${DOMAIN}`) && !PathPrefix(`/admin`)
      - traefik.http.services.headscale.loadbalancer.server.port=8080
      - traefik.http.routers.headscale-metrics.entrypoints=websecure_private
      - traefik.http.routers.headscale-metrics.rule=Host(`headscale-metrics.vpn.${DOMAIN}`)
      - traefik.http.services.headscale-metrics.loadbalancer.server.port=9090

  headplane:
    image: ghcr.io/tale/headplane:0.6.2
    restart: unless-stopped
    depends_on:
      - headscale
    volumes:
      - ./headplane/config.yaml:/etc/headplane/config.yaml:ro
      - ./headscale/config.yaml:/etc/headscale/config.yaml:ro
      - ./headscale/acls.hujson:/etc/headscale/acls.hujson:ro
      - headplane_data:/var/lib/headplane
    networks:
      - headscale_private_net
      - traefik_public_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.headplane.entrypoints=websecure_private
      - traefik.http.routers.headplane.rule=Host(`vpn.${DOMAIN}`) && PathPrefix(`/admin`)
      - traefik.http.services.headplane.loadbalancer.server.port=3000

volumes:
  headscale_data:
  headplane_data:

networks:
  headscale_private_net:
    internal: false
