services:
  nextcloud:
    image: docker.io/library/nextcloud:31.0.14-apache
    restart: unless-stopped
    depends_on:
      nextcloud_postgres:
        condition: service_healthy
      nextcloud_redis:
        condition: service_healthy
    environment:
      # Database
      POSTGRES_HOST: nextcloud_postgres
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
      # Redis
      REDIS_HOST: nextcloud_redis
      REDIS_HOST_PASSWORD: ${NEXTCLOUD_REDIS_PASSWORD}
      # SMTP
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_NAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE_STRING}
      MAIL_FROM_ADDRESS: nextcloud
      MAIL_DOMAIN: ${DOMAIN}
      # Nextcloud
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.${DOMAIN}
      # Proxy settings
      APACHE_DISABLE_REWRITE_IP: 1
      TRUSTED_PROXIES: traefik
      # File Limits (Aligns with Traefik/AppSec body limit)
      PHP_UPLOAD_LIMIT: ${MAX_BODY_SIZE_MB}
      PHP_MEMORY_LIMIT: 512M
      APACHE_BODY_LIMIT: ${MAX_BODY_SIZE_BYTES}
    volumes:
      - nextcloud_app:/var/www/html
      - ${NEXTCLOUD_STORAGE_LOCATION}:/var/www/html/data
    networks:
      - nextcloud_net
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN}`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=80
      # CalDAV/CardDAV redirects
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/ca(l|rd)dav
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/
      - traefik.http.routers.nextcloud.middlewares=nextcloud-caldav

  nextcloud_postgres:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
    volumes:
      - nextcloud_db_data:/var/lib/postgresql/data
    networks:
      - nextcloud_net

  nextcloud_redis:
    image: docker.io/valkey/valkey:8.1
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - valkey-cli -a ${NEXTCLOUD_REDIS_PASSWORD} ping | grep PONG
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 3s
    environment:
      VALKEY_EXTRA_FLAGS: --requirepass ${NEXTCLOUD_REDIS_PASSWORD}
    networks:
      - nextcloud_net

volumes:
  nextcloud_app:
  nextcloud_db_data:

networks:
  nextcloud_net:
    internal: false

