x-authentik_env: &authentik_env
  # Database Settings
  AUTHENTIK_POSTGRESQL__HOST: authentik_postgresql
  AUTHENTIK_POSTGRESQL__NAME: ${AUTHENTIK_PG_DB}
  AUTHENTIK_POSTGRESQL__USER: ${AUTHENTIK_PG_USER}
  AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_PG_PASS}

  # Secret Key
  AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}

  # SMTP Settings
  AUTHENTIK_EMAIL__HOST: ${SMTP_HOST}
  AUTHENTIK_EMAIL__PORT: ${SMTP_PORT}
  AUTHENTIK_EMAIL__USERNAME: ${SMTP_USERNAME}
  AUTHENTIK_EMAIL__PASSWORD: ${SMTP_PASSWORD}
  AUTHENTIK_EMAIL__USE_TLS: ${SMTP_USE_TLS}
  AUTHENTIK_EMAIL__USE_SSL: ${SMTP_USE_SSL}
  AUTHENTIK_EMAIL__TIMEOUT: 30
  AUTHENTIK_EMAIL__FROM: Authentik <no-reply@${DOMAIN}>

services:
  authentik_server:
    image: ghcr.io/goauthentik/server:2026.2.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "${PUID}:${PGID}"
    depends_on:
      authentik_postgresql:
        condition: service_healthy
    command: server
    environment:
      <<: [*authentik_env]
    volumes:
      - authentik_data:/data
      - ./templates:/templates:ro
    networks:
      - authentik_private_net
      - traefik_public_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.authentik.entrypoints=websecure
      - traefik.http.routers.authentik.rule=Host(`auth.server.${DOMAIN}`)
      - traefik.http.services.authentik.loadbalancer.server.port=9000

  authentik_worker:
    image: ghcr.io/goauthentik/server:2026.2.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "${PUID}:${PGID}"
    depends_on:
      authentik_postgresql:
        condition: service_healthy
    command: worker
    environment:
      <<: [*authentik_env]
    volumes:
      - authentik_data:/data
      - ./templates:/templates:ro
      - authentik_certs:/certs
    networks:
      - authentik_private_net

  authentik_postgresql:
    image: docker.io/library/postgres:18.3-alpine3.23
    restart: unless-stopped
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    environment:
      POSTGRES_DB: ${AUTHENTIK_PG_DB}
      POSTGRES_USER: ${AUTHENTIK_PG_USER}
      POSTGRES_PASSWORD: ${AUTHENTIK_PG_PASS}
    volumes:
      - authentik_db_data:/var/lib/postgresql/data
    networks:
      - authentik_private_net

volumes:
  authentik_data:
  authentik_certs:
  authentik_db_data:

networks:
  authentik_private_net:
    internal: false
