name: homelab_server

include:
  # Infrastructure services
  - services/traefik/compose.yaml
  - services/adguard/compose.yaml
  - services/authentik/compose.yaml

  # Open source applications
  - services/ollama/compose.yaml
  - services/open_webui/compose.yaml
  - services/penpot/compose.yaml
  - services/vaultwarden/compose.yaml

  # Self developed applications
  - services/code_runner/compose.yaml
  - services/lichobi/compose.yaml
