x-penpot_flags: &penpot_flags
  PENPOT_FLAGS: enable-smtp enable-login-with-oidc enable-oidc-registration disable-login-with-password disable-registration disable-email-verification

x-penpot_public_uri: &penpot_public_uri
  PENPOT_PUBLIC_URI: https://penpot.${DOMAIN}

x-penpot_http_body_size: &penpot_http_body_size
  # Max body size (30MiB); Used for plain requests, should never be greater than multi-part size
  PENPOT_HTTP_SERVER_MAX_BODY_SIZE: 31457280
  # Max multipart body size (350MiB)
  PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE: 367001600

x-penpot_secret_key: &penpot_secret_key
  PENPOT_SECRET_KEY: ${PENPOT_SECRET_KEY}

services:
  penpot_frontend:
    image: docker.io/penpotapp/frontend:2.12.1
    restart: unless-stopped
    depends_on:
      - penpot_backend
      - penpot_exporter
    environment:
      <<: [*penpot_flags, *penpot_http_body_size]
    volumes:
      - penpot_assets:/opt/data/assets
    networks:
      - penpot_net
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.penpot.entrypoints=websecure
      - traefik.http.routers.penpot.rule=Host(`penpot.${DOMAIN}`)
      - traefik.http.services.penpot.loadbalancer.server.port=8080

  penpot_backend:
    image: docker.io/penpotapp/backend:2.12.1
    restart: unless-stopped
    depends_on:
      penpot_postgres:
        condition: service_healthy
      penpot_valkey:
        condition: service_healthy
    environment:
      <<: [*penpot_flags, *penpot_public_uri, *penpot_http_body_size, *penpot_secret_key]
      PENPOT_DATABASE_URI: postgresql://penpot_postgres/${PENPOT_PG_DB}
      PENPOT_DATABASE_USERNAME: ${PENPOT_PG_USER}
      PENPOT_DATABASE_PASSWORD: ${PENPOT_PG_PASS}
      PENPOT_REDIS_URI: redis://penpot_valkey/0
      PENPOT_ASSETS_STORAGE_BACKEND: assets-fs
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: /opt/data/assets
      PENPOT_SMTP_DEFAULT_FROM: Penpot <penpot@${DOMAIN}>
      PENPOT_SMTP_DEFAULT_REPLY_TO: ${ORG_NAME} Support <support@${DOMAIN}>
      PENPOT_SMTP_HOST: ${SMTP_HOST}
      PENPOT_SMTP_PORT: ${SMTP_PORT}
      PENPOT_SMTP_USERNAME: ${SMTP_USERNAME}
      PENPOT_SMTP_PASSWORD: ${SMTP_PASSWORD}
      PENPOT_SMTP_TLS: ${SMTP_USE_TLS}
      PENPOT_SMTP_SSL: ${SMTP_USE_SSL}
      PENPOT_OIDC_CLIENT_ID: ${PENPOT_OIDC_ID}
      PENPOT_OIDC_CLIENT_SECRET: ${PENPOT_OIDC_SECRET}
      PENPOT_OIDC_BASE_URI: https://auth.${DOMAIN}/application/o/${PENPOT_OIDC_SLUG}/
    volumes:
      - penpot_assets:/opt/data/assets
    networks:
      - penpot_net

  penpot_exporter:
    image: docker.io/penpotapp/exporter:2.12.1
    restart: unless-stopped
    depends_on:
      penpot_valkey:
        condition: service_healthy
    environment:
      <<: [*penpot_secret_key]
      PENPOT_PUBLIC_URI: http://penpot_frontend:8080
      PENPOT_REDIS_URI: redis://penpot_valkey/0
    networks:
      - penpot_net

  penpot_postgres:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    stop_signal: SIGINT
    environment:
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_DB: ${PENPOT_PG_DB}
      POSTGRES_USER: ${PENPOT_PG_USER}
      POSTGRES_PASSWORD: ${PENPOT_PG_PASS}
    volumes:
      - penpot_db_data:/var/lib/postgresql/data
    networks:
      - penpot_net
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s

  penpot_valkey:
    image: docker.io/valkey/valkey:8.1
    restart: unless-stopped
    environment:
      VALKEY_EXTRA_FLAGS: --maxmemory 128mb --maxmemory-policy volatile-lfu
    networks:
      - penpot_net
    healthcheck:
      test:
        - CMD-SHELL
        - valkey-cli ping | grep PONG
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 3s

volumes:
  penpot_assets:
  penpot_db_data:

networks:
  penpot_net:
    internal: false
