services:
  adguard:
    image: docker.io/adguard/adguardhome:v0.107.71
    restart: unless-stopped
    ports:
      - ${SERVER_LAN_IP}:53:53/tcp
      - ${SERVER_LAN_IP}:53:53/udp
      # - 3000:3000/tcp # uncomment for initial setup
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_config:/opt/adguardhome/conf
    networks:
      - adguard_net
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.entrypoints=websecure
      - traefik.http.routers.adguard.rule=Host(`adguard.internal.${DOMAIN}`)
      - traefik.http.routers.adguard.middlewares=authentik_auth@file
      - traefik.http.services.adguard.loadbalancer.server.port=80

volumes:
  adguard_data:
  adguard_config:

networks:
  adguard_net:
    internal: false
