services:
  immich_server:
    image: ghcr.io/immich-app/immich-server:v2.5.6
    restart: unless-stopped
    depends_on:
      - immich_redis
      - immich_database
    healthcheck:
      disable: false
    environment:
      TZ: ${SERVER_TZ}
      IMMICH_MACHINE_LEARNING_URL: http://immich_machine_learning:3003
      DB_HOSTNAME: immich_database
      DB_DATABASE_NAME: ${IMMICH_DB_DATABASE_NAME}
      DB_USERNAME: ${IMMICH_DB_USERNAME}
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      REDIS_HOSTNAME: immich_redis
      REDIS_PASSWORD: ${IMMICH_REDIS_PASS}
    volumes:
      - ${IMMICH_STORAGE_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - immich_net
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)
      - traefik.http.services.immich.loadbalancer.server.port=2283
    devices:
      - /dev/dri:/dev/dri # for intel quick sync video encoding

  immich_machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.6-cuda
    restart: unless-stopped
    healthcheck:
      disable: false
    volumes:
      - immich_model_cache:/cache
    networks:
      - immich_net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  immich_redis:
    image: docker.io/valkey/valkey:9.0
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    environment:
      VALKEY_EXTRA_FLAGS: --requirepass ${IMMICH_REDIS_PASS}
    networks:
      - immich_net

  immich_database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    restart: unless-stopped
    shm_size: 128mb
    healthcheck:
      disable: false
    environment:
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - immich_db_data:/var/lib/postgresql/data
    networks:
      - immich_net

volumes:
  immich_model_cache:
  immich_db_data:

networks:
  immich_net:
    internal: false
